### ISSUE TITLE
(node:34) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by TianTopup** [imlinhanchao/translator-promise#1]
(node:34) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
at getTkk (/app/node_modules/translator-promise/inc/translate.js:10:17)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by imlinhanchao** [comment]
It's fixed. pls update to version 1.0.5 .
